/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_naver_android_pholar_util_imagestabilizer_MainActivity */

#ifndef _Included_com_naver_android_pholar_util_imagestabilizer_MainActivity
#define _Included_com_naver_android_pholar_util_imagestabilizer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_naver_android_pholar_util_imagestabilizer_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_naver_android_pholar_util_imagestabilizer_MainActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
