/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_naver_android_pholar_util_imagestabilizer_ImageStabilizer */

#ifndef _Included_com_naver_android_pholar_util_imagestabilizer_ImageStabilizer
#define _Included_com_naver_android_pholar_util_imagestabilizer_ImageStabilizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_naver_android_pholar_util_imagestabilizer_ImageStabilizer
 * Method:    getGrayImages
 * Signature: ([J[JI)I
 */
JNIEXPORT jint JNICALL Java_com_naver_android_pholar_util_imagestabilizer_ImageStabilizer_getGrayImages
  (JNIEnv *, jobject, jlongArray, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
